apiVersion: v1
kind: Service
metadata:
  name: ecommerce-web
  namespace: ecommerce
  labels:
    app: ecommerce-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ecommerce-web
